name: Deploy POC

on:
  push:
    branches:
      - poc

jobs:
  deploy:
    uses: taif-ix/ikarkhana_api/.github/workflows/reusable-cloudrun.yml@main
    with:
      service_name: my-api-poc
      project_id: my-gcp-project
      region: us-central1
      repository: docker-images
      image_name: my-api
      dockerfile: ./Dockerfile

    secrets:
      workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
      service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}