name: Deploy dev

on:
  push:
    branches:
      - dev

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    uses: indixpert-technologies/int-ikarkhana-ai-api/.github/workflows/reusable-cloudrun.yml@main
    with:
      service_name: ikarkhana-test
      project_id: gen-lang-client-0148520460
      region: asia-south1
      repository: cloud-run-source-deploy
      image_name: ikarkhana-test
      dockerfile: ./Dockerfile
      port: "8080"  

    secrets:
      workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
      service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}